/**
 * @author Habib Ismail Al Qadri
 * @app Quran Saku
 */
import { DoaItem, Surah } from "./types";

export const DEFAULT_CITIES = [
  { id: "1301", lokasi: "KOTA JAKARTA" },
  { id: "1210", lokasi: "KOTA BANDUNG" },
  { id: "1638", lokasi: "KOTA SURABAYA" },
  { id: "1430", lokasi: "KOTA YOGYAKARTA" },
  { id: "0115", lokasi: "KOTA MEDAN" },
  { id: "2212", lokasi: "KOTA MAKASSAR" },
  { id: "1708", lokasi: "KOTA DENPASAR" },
  { id: "1505", lokasi: "KOTA SEMARANG" },
  { id: "0814", lokasi: "KOTA PALEMBANG" },
  { id: "1810", lokasi: "KOTA BALIKPAPAN" },
  { id: "2115", lokasi: "KOTA MANADO" }
];

export const STATIC_SURAHS: Surah[] = [
  { nomor: 1, nama: "Al-Fatihah", namaLatin: "Al-Fatihah", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Pembukaan", deskripsi: "Surat pembuka Al-Qur'an." },
  { nomor: 2, nama: "Al-Baqarah", namaLatin: "Al-Baqarah", jumlahAyat: 286, tempatTurun: "Madinah", arti: "Sapi Betina", deskripsi: "Surat terpanjang dalam Al-Qur'an." },
  { nomor: 3, nama: "Ali 'Imran", namaLatin: "Ali 'Imran", jumlahAyat: 200, tempatTurun: "Madinah", arti: "Keluarga Imran", deskripsi: "Membahas ketauhidan dan risalah Isa as." },
  { nomor: 4, nama: "An-Nisa'", namaLatin: "An-Nisa'", jumlahAyat: 176, tempatTurun: "Madinah", arti: "Wanita", deskripsi: "Membahas hukum waris, pernikahan, dan hak wanita." },
  { nomor: 5, nama: "Al-Ma'idah", namaLatin: "Al-Ma'idah", jumlahAyat: 120, tempatTurun: "Madinah", arti: "Hidangan", deskripsi: "Menetapkan makanan halal-haram dan hukum dhohir." },
  { nomor: 6, nama: "Al-An'am", namaLatin: "Al-An'am", jumlahAyat: 165, tempatTurun: "Mekah", arti: "Binatang Ternak", deskripsi: "Menjelaskan asas-asas keimanan secara mendalam." },
  { nomor: 7, nama: "Al-A'raf", namaLatin: "Al-A'raf", jumlahAyat: 206, tempatTurun: "Mekah", arti: "Tempat yang Tinggi", deskripsi: "Mengisahkan perjuangan para rasul melawan kesombongan." },
  { nomor: 8, nama: "Al-Anfal", namaLatin: "Al-Anfal", jumlahAyat: 75, tempatTurun: "Madinah", arti: "Rampasan Perang", deskripsi: "Menguraikan tuntunan moral dalam perang Badar." },
  { nomor: 9, nama: "At-Taubah", namaLatin: "At-Taubah", jumlahAyat: 129, tempatTurun: "Madinah", arti: "Pengampunan", deskripsi: "Membatalkan perjanjian dengan kaum musyrik karena pengkhianatan." },
  { nomor: 10, nama: "Yunus", namaLatin: "Yunus", jumlahAyat: 109, tempatTurun: "Mekah", arti: "Yunus", deskripsi: "Menegaskan kebenaran wahyu dan kekuasaan Allah Swt." },
  { nomor: 11, nama: "Hud", namaLatin: "Hud", jumlahAyat: 123, tempatTurun: "Mekah", arti: "Hud", deskripsi: "Berisi kisah-kisah kaum terdahulu yang mendustakan rasul." },
  { nomor: 12, nama: "Yusuf", namaLatin: "Yusuf", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Yusuf", deskripsi: "Mengisahkan perjalanan hidup Nabi Yusuf as secara runtut." },
  { nomor: 13, nama: "Ar-Ra'd", namaLatin: "Ar-Ra'd", jumlahAyat: 43, tempatTurun: "Madinah", arti: "Guruh", deskripsi: "Menjelaskan ketetapan takdir, wahyu, dan sunnatullah." },
  { nomor: 14, nama: "Ibrahim", namaLatin: "Ibrahim", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Ibrahim", deskripsi: "Membahas hakikat tauhid dan rasa syukur atas nikmat." },
  { nomor: 15, nama: "Al-Hijr", namaLatin: "Al-Hijr", jumlahAyat: 99, tempatTurun: "Mekah", arti: "Gunung Batu", deskripsi: "Menjamin penjagaan keaslian Al-Qur'an sepanjang masa." },
  { nomor: 16, nama: "An-Nahl", namaLatin: "An-Nahl", jumlahAyat: 128, tempatTurun: "Mekah", arti: "Lebah", deskripsi: "Mengajak merenungi berbagai tanda kebesaran Allah di alam raya." },
  { nomor: 17, nama: "Al-Isra'", namaLatin: "Al-Isra'", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Perjalanan Malam", deskripsi: "Mengisahkan Isra Mikraj Nabi Muhammad saw dan hukum moral." },
  { nomor: 18, nama: "Al-Kahf", namaLatin: "Al-Kahf", jumlahAyat: 110, tempatTurun: "Mekah", arti: "Goa", deskripsi: "Menjelaskan kisah Ashabul Kahfi, pemilik kebun, Musa & Khidir." },
  { nomor: 19, nama: "Maryam", namaLatin: "Maryam", jumlahAyat: 98, tempatTurun: "Mekah", arti: "Maryam", deskripsi: "Menceritakan keajaiban kelahiran Yahya as dan Isa as." },
  { nomor: 20, nama: "Taha", namaLatin: "Taha", jumlahAyat: 135, tempatTurun: "Mekah", arti: "Taha", deskripsi: "Mengisahkan perjuangan Nabi Musa as membebaskan Bani Israil." },
  { nomor: 21, nama: "Al-Anbiya'", namaLatin: "Al-Anbiya'", jumlahAyat: 112, tempatTurun: "Mekah", arti: "Para Nabi", deskripsi: "Kisah perjuangan, doa, dan kesabaran para nabi Allah." },
  { nomor: 22, nama: "Al-Hajj", namaLatin: "Al-Hajj", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Haji", deskripsi: "Menegaskan kewajiban haji dan pengagungan syiar Allah." },
  { nomor: 23, nama: "Al-Mu'minun", namaLatin: "Al-Mu'minun", jumlahAyat: 118, tempatTurun: "Mekah", arti: "Orang-orang Mukmin", deskripsi: "Memaparkan sifat-sifat mulia yang membawa keberuntungan." },
  { nomor: 24, nama: "An-Nur", namaLatin: "An-Nur", jumlahAyat: 64, tempatTurun: "Madinah", arti: "Cahaya", deskripsi: "Memberikan tuntunan moral, adab bertamu, dan hijab." },
  { nomor: 25, nama: "Al-Furqan", namaLatin: "Al-Furqan", jumlahAyat: 77, tempatTurun: "Mekah", arti: "Pembeda", deskripsi: "Al-Qur'an sebagai pembeda antara haq dan batil." },
  { nomor: 26, nama: "Asy-Syara'", namaLatin: "Asy-Syara'", jumlahAyat: 227, tempatTurun: "Mekah", arti: "Para Penyair", deskripsi: "Menegaskan bahwa wahyu Al-Qur'an bukanlah syair." },
  { nomor: 27, nama: "An-Naml", namaLatin: "An-Naml", jumlahAyat: 93, tempatTurun: "Mekah", arti: "Semut", deskripsi: "Mengisahkan Sulaiman as, semut, burung hud-hud, & ratu Balqis." },
  { nomor: 28, nama: "Al-Qasas", namaLatin: "Al-Qasas", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Cerita-cerita", deskripsi: "Menceritakan detail masa kecil Nabi Musa as menantang Firaun." },
  { nomor: 29, nama: "Al-'Ankabut", namaLatin: "Al-'Ankabut", jumlahAyat: 69, tempatTurun: "Mekah", arti: "Laba-laba", deskripsi: "Perumpamaan rapuhnya berhala seperti rumah laba-laba." },
  { nomor: 30, nama: "Ar-Rum", namaLatin: "Ar-Rum", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Romawi", deskripsi: "Kemenangan Romawi yang diprediksi wahyu dan ayat penciptaan." },
  { nomor: 31, nama: "Luqman", namaLatin: "Luqman", jumlahAyat: 34, tempatTurun: "Mekah", arti: "Luqman", deskripsi: "Nasihat mendasar Luqman al-Hakim kepada putranya." },
  { nomor: 32, nama: "As-Sajdah", namaLatin: "As-Sajdah", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Sujud", deskripsi: "Keagungan hari kebangkitan dan perintah bersujud khusyuk." },
  { nomor: 33, nama: "Al-Ahzab", namaLatin: "Al-Ahzab", jumlahAyat: 73, tempatTurun: "Madinah", arti: "Golongan yang Bersekutu", deskripsi: "Perang Ahzab (Khandaq) dan adab terhadap keluarga nabi." },
  { nomor: 34, nama: "Saba'", namaLatin: "Saba'", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Saba'", deskripsi: "Kehancuran bendungan Ma'rib karena kufur nikmat." },
  { nomor: 35, nama: "Fatir", namaLatin: "Fatir", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Pencipta", deskripsi: "Menjelaskan bahwa Allah Swt adalah Pencipta tunggal alam raya." },
  { nomor: 36, nama: "Yasin", namaLatin: "Yasin", jumlahAyat: 83, tempatTurun: "Mekah", arti: "Yasin", deskripsi: "Dikenal sebagai jantung Al-Qur'an, membahas hari berbangkit." },
  { nomor: 37, nama: "As-Saffat", namaLatin: "As-Saffat", jumlahAyat: 182, tempatTurun: "Mekah", arti: "Barisan-barisan", deskripsi: "Mengisahkan kesetiaan malaikat dan pengorbanan Ibrahim as." },
  { nomor: 38, nama: "Sad", namaLatin: "Sad", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Sad", deskripsi: "Ketabahan Nabi Ayyub as dan kemuliaan Nabi Dawud as." },
  { nomor: 39, nama: "Az-Zumar", namaLatin: "Az-Zumar", jumlahAyat: 75, tempatTurun: "Mekah", arti: "Rombongan-rombongan", deskripsi: "Gambaran manusia digiring ke surga atau neraka berbondong-bondong." },
  { nomor: 40, nama: "Ghafir", namaLatin: "Ghafir", jumlahAyat: 85, tempatTurun: "Mekah", arti: "Maha Pengampun", deskripsi: "Menegaskan luasnya ampunan Allah bagi hamba yang bertaubat." },
  { nomor: 41, nama: "Fussilat", namaLatin: "Fussilat", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Yang Dijelaskan", deskripsi: "Al-Qur'an sebagai penawar rindu, petunjuk, dan obat sanubari." },
  { nomor: 42, nama: "Asy-Syura", namaLatin: "Asy-Syura", jumlahAyat: 53, tempatTurun: "Mekah", arti: "Musyawarah", deskripsi: "Tuntunan musyawarah dalam menyelesaikan berbagai perkara." },
  { nomor: 43, nama: "Az-Zukhruf", namaLatin: "Az-Zukhruf", jumlahAyat: 89, tempatTurun: "Mekah", arti: "Perhiasan", deskripsi: "Kecaman terhadap pemuja harta dan perhiasan dunia berlebih." },
  { nomor: 44, nama: "Ad-Dukhan", namaLatin: "Ad-Dukhan", jumlahAyat: 59, tempatTurun: "Mekah", arti: "Kabut", deskripsi: "Peringatan azab berupa kabut tebal menyiksa kaum pembangkang." },
  { nomor: 45, nama: "Al-Jasiyah", namaLatin: "Al-Jasiyah", jumlahAyat: 37, tempatTurun: "Mekah", arti: "Yang Berlutut", deskripsi: "Setiap umat berlutut gemetar pada hari perhitungan amal." },
  { nomor: 46, nama: "Al-Ahqaf", namaLatin: "Al-Ahqaf", jumlahAyat: 35, tempatTurun: "Mekah", arti: "Bukit-bukit Pasir", deskripsi: "Kisah kaum Ad mendustakan Nabi Hud as di bukit pasir." },
  { nomor: 47, nama: "Muhammad", namaLatin: "Muhammad", jumlahAyat: 38, tempatTurun: "Madinah", arti: "Muhammad", deskripsi: "Panduan jihad mempertahankan diri di jalan kebenaran." },
  { nomor: 48, nama: "Al-Fath", namaLatin: "Al-Fath", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Kemenangan", deskripsi: "Kemenangan nyata dalam perdamaian melalui perjanjian Hudaibiyah." },
  { nomor: 49, nama: "Al-Hujurat", namaLatin: "Al-Hujurat", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Kamar-kamar", deskripsi: "Hukum etika sosial, larangan membicarakan aib sesama." },
  { nomor: 50, nama: "Qaf", namaLatin: "Qaf", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Qaf", deskripsi: "Proses kematian, sakaratul maut, dan tiupan sangkakala." },
  { nomor: 55, nama: "Ar-Rahman", namaLatin: "Ar-Rahman", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Maha Pemurah", deskripsi: "Menyebutkan nikmat Tuhan berulang-ulang: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?'" },
  { nomor: 56, nama: "Al-Waqi'ah", namaLatin: "Al-Waqi'ah", jumlahAyat: 96, tempatTurun: "Mekah", arti: "Hari Kiamat", deskripsi: "Menggambarkan kenikmatan Ashabul Yamin dan siksa Ashabul Syimal." },
  { nomor: 67, nama: "Al-Mulk", namaLatin: "Al-Mulk", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Kerajaan", deskripsi: "Pelindung dari siksa kubur, dianjurkan dibaca setiap malam." },
  { nomor: 112, nama: "Al-Ikhlas", namaLatin: "Al-Ikhlas", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Ikhlas", deskripsi: "Ringkasan konsep ketauhidan mutlak dalam Islam." },
  { nomor: 113, nama: "Al-Falaq", namaLatin: "Al-Falaq", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Waktu Subuh", deskripsi: "Doa memohon perlindungan dari kejahatan malam dan sihir." },
  { nomor: 114, nama: "An-Nas", namaLatin: "An-Nas", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Manusia", deskripsi: "Doa perlindungan dari bisikan jahat setan pembisik hati." }
];

export const STATIC_DOA: DoaItem[] = [
  {
    judul: "Doa Memohon Kebaikan Dunia Akhirat (Sapu Jagat)",
    arab: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    latin: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan waqina 'adhaban-nar",
    terjemah: "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.",
    sumber: "QS. Al-Baqarah: 201",
    kategori: "Penting"
  },
  {
    judul: "Doa Sebelum Makan",
    arab: "اَللّٰهُمَّ بَارِكْ لَنَا فِيْمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ",
    latin: "Allahumma barik lana fima razaqtana waqina 'adhaban-nar",
    terjemah: "Ya Allah, berkahilah kami atas rezeki yang telah Engkau limpahkan kepada kami dan peliharalah kami dari siksa neraka.",
    sumber: "Hadis Riwayat Ibn Sunni",
    kategori: "Harian"
  },
  {
    judul: "Doa Setelah Makan",
    arab: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    latin: "Alhamdu lillahil-ladhi at'amana wasaqana waja'alana muslimin",
    terjemah: "Segala puji bagi Allah yang telah memberi kami makan dan minum, serta menjadikan kami termasuk golongan orang-orang muslim.",
    sumber: "Hadis Riwayat Abu Dawud",
    kategori: "Harian"
  },
  {
    judul: "Doa Sebelum Tidur",
    arab: "بِاسْمِكَ اللَّهُمَّ أَحْيَا وَبِاسْمِكَ أَمُوتُ",
    latin: "Bismika l-lahumma ahya wa bismika amut",
    terjemah: "Dengan nama-Mu ya Allah aku hidup, dan dengan nama-Mu aku mati.",
    sumber: "Hadis Riwayat Bukhari & Muslim",
    kategori: "Harian"
  },
  {
    judul: "Doa Bangun Tidur",
    arab: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    latin: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilaihin-nusyur",
    terjemah: "Segala puji bagi Allah yang telah menghidupkan kami kembali setelah mematikan kami, dan kepada-Nya lah tempat kembali.",
    sumber: "Hadis Riwayat Bukhari",
    kategori: "Harian"
  },
  {
    judul: "Doa Kedua Orang Tua",
    arab: "رَبَّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    latin: "Rabbighfir li waliwalidayya warhamhuma kama rabbayani saghira",
    terjemah: "Ya Tuhanku, ampunilah aku dan kedua orang tuaku, dan sayangilah mereka berdua sebagaimana mereka telah mendidikku di waktu kecil.",
    sumber: "QS. Al-Isra': 24",
    kategori: "Keluarga"
  },
  {
    judul: "Doa Memohon Keteguhan Iman",
    arab: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً ۚ إِنَّكَ أَنْتَ الْوَهَّابُ",
    latin: "Rabbana la tuzigh qulubana ba'da idh hadaitana wahab lana mil-ladunka rahmatan innaka antal-Wahhab",
    terjemah: "Ya Tuhan kami, janganlah Engkau condongkan hati kami kepada kesesatan setelah Engkau berikan petunjuk kepada kami, dan karuniakanlah kepada kami rahmat dari sisi-Mu. Sesungguhnya Engkau-lah Maha Pemberi.",
    sumber: "QS. Ali 'Imran: 8",
    kategori: "Ibadah"
  },
  {
    judul: "Doa Memohon Kelapangan Hati (Nabi Musa)",
    arab: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي",
    latin: "Rabbisy-syrah li sadri, wayassir li amri, wahlul 'uqdatan mil lisani, yafqahu qauli",
    terjemah: "Ya Tuhanku, lapangkanlah dadaku, mudahkanlah urusanku, dan lepaskanlah kekakuan lidahku agar mereka mengerti perkataanku.",
    sumber: "QS. Taha: 25-28",
    kategori: "Penting"
  },
  {
    judul: "Doa Nabi SAW (Menyatukan Hati dan Memohon Keselamatan)",
    arab: "اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا وَاهْدِنَا سُبُلَ السَّلَامِ وَنَجِّنَا مِنَ الظُّلُمَاتِ إِلَى النُّورِ وَجَنِّبْنَا الْفَوَاحِشَ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ وَبَارِكْ لَنَا فِي أَسْمَاعِنَا وَأَبْصَارِنَا وَقُلُوبِنَا وَأَزْوَاجِنَا وَذُرِّيَّاتِنَا وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ وَاجْعَلْنَا شَاكِرِينَ لِنِعْمَتِكَ مُثْنِينَ بِهَا عَلَيْكَ، قَابِلِينَ لَهَا وَأَتِمَّهَا عَلَيْنَا",
    latin: "Allahumma allif baina qulubina, wa ash-lih dzata bainina, wahdina subulas-salam, wa najjina minaz-zulumati ilan-nur, wa jannibnal fawahisya ma zahara minha wama batan, wa barik lana fi asma'ina wa absarina, wa qulubina wa azwajina wa dzurriyyatina, wa tub 'alaina innaka antat-tawwabur-rahim, waj'alna syakirina lini'matika muthnina biha 'alaika qabilina laha, wa atimmaha 'alaina.",
    terjemah: "Ya Allah, satukanlah hati-hati kami, perbaikilah keadaan di antara kami, tunjukilah kami jalan-jalan keselamatan, selamatkanlah kami dari kegelapan menuju cahaya, jauhkanlah kami dari perbuatan keji yang tampak maupun yang tersembunyi. Berkahilah pendengaran, penglihatan, hati, pasangan-pasangan, dan keturunan kami. Terimalah taubat kami, sesungguhnya Engkau Maha Penerima Taubat lagi Maha Penyayang. Jadikanlah kami orang-orang yang bersyukur atas nikmat-Mu, yang memuji-Mu dengan nikmat tersebut dan menerimanya, serta sempurnakanlah nikmat tersebut atas kami.",
    sumber: "HR. Abu Dawud no. 969, Al-Hakim",
    kategori: "Keluarga"
  },
  {
    judul: "Doa Akhir Tahun",
    arab: "اَللَّهُمَّ مَا عَمِلْتُ مِنْ عَمَلٍ فِي السَّنَةِ الْمَاضِيَةِ وَلَمْ تَرْضَهُ، وَنَسِيتُهُ وَلَمْ تَنْسَهُ، وَحَلُمْتَ عَنِّي مَعَ قُدْرَتِكَ عَلَى عُقُوبَتِي، وَدَعَوْتَنِي إِلَى التَّوْبَةِ بَعْدَ جَرَاءَتِي عَلَيْكَ. اَللَّهُمَّ إِنِّي أَسْتَغْفِرُكَ مِنْهُ فَاغْفِرْ لِي، وَمَا عَمِلْتُ مِنْ عَمَلٍ تَرْضَاهُ وَوَعَدْتَنِي عَلَيْهِ الثَّوَابَ وَالْغُفْرَانَ فَتَقَبَّلْهُ مِنِّي، وَلَا تَقْطَعْ رَجَائِي مِنْكَ يَا كَرِيمُ يَا أَرْحَمَ الرَّاحِمِينَ.",
    latin: "Allahumma ma 'amiltu min 'amalin fis-sanatil madhiyati walam tardhahu, wa nasituhu walam tansahu, wa halumta 'anni ma'a qudratika 'ala 'uqubati, wa da'autani ilat-taubati ba'da jara'ati 'alaika. Allahumma inni astaghfiruka minhu faghfirli, wama 'amiltu min 'amalin tardhahu wa wa'adtani 'alaihith-thawaba wal ghufrana fataqabbalhu minni, wala taqta' raja'i minka ya karimu ya arhamar-rahimin.",
    terjemah: "Ya Allah, apa yang telah aku kerjakan di tahun lalu, yang Engkau tidak ridhai dan aku melupakannya, sedang Engkau tidak melupakannya; dan Engkau bersikap lembut kepadaku, padahal Engkau berkuasa menyiksaku; dan Engkau masih menyeruku bertaubat setelah kelancanganku terhadap-Mu. Ya Allah, sesungguhnya aku memohon ampun kepada-Mu dari amal itu, maka ampunilah aku. Dan dari amalku yang Engkau ridhai dan Engkau janjikan pahala dan ampunan, maka terimalah dariku, dan janganlah Engkau putuskan harapanku dari-Mu, Wahai Yang Maha Mulia, Wahai Yang Maha Penyayang.",
    sumber: "Umum",
    kategori: "Penting"
  },
  {
    judul: "Doa Awal Tahun",
    arab: "اَللَّهُمَّ أَنْتَ الأَبَدِيُّ الْقَدِيمُ الأَوَّلُ، وَعَلَى فَضْلِكَ الْعَظِيمِ وَكَرَمِ جُودِكَ الْمُعَوَّلِ، وَهَذَا عَامٌ جَدِيدٌ قَدْ أَقْبَلَ، أَسْأَلُكَ الْعِصْمَةَ فِيهِ مِنَ الشَّيْطَانِ وَأَوْلِيَائِهِ، وَالْعَوْنَ عَلَى هَذِهِ النَّفْسِ الأَمَّارَةِ بِالسُّوءِ، وَالاِشْتِغَالَ بِمَا يُقَرِّبُنِي إِلَيْكَ زُلْفَى يَا ذَا الْجَلالِ وَالإِكْرَامِ.",
    latin: "Allahumma antal-abadiyyul-qadimul-awwal, wa 'ala fadhlikal-'azhimi wa karami judikal-mu'awwal, wa hadza 'amun jadidun qad aqbala, as'alukal-`ismata fihi minash-shaitani wa auliya'ih, wal-'auna 'ala hadzihin-nafsil-ammarati bis-su'i, wal-ishtighala bima yuqarribuni ilaika zulfa ya dzal-jalali wal-ikram.",
    terjemah: "Ya Allah, Engkau Yang Abadi, Qadim, dan Awal. Dan hanya pada karunia-Mu yang agung dan kedermawanan-Mu tempat berlindung. Dan ini adalah tahun baru yang telah datang, aku memohon perlindungan di dalamnya dari setan dan bala tentaranya, dan pertolongan untuk menundukkan nafsu yang selalu menyuruh kepada kejahatan, dan disibukkan dengan hal-hal yang mendekatkanku kepada-Mu sebegitu dekat, Wahai Dzat yang Memiliki Kebesaran dan Kemuliaan.",
    sumber: "Umum",
    kategori: "Penting"
  },
  {
    judul: "Doa Asyura",
    arab: "سُبْحَانَ اللهِ مِلْءَ الْمِيزَانِ وَمُنْتَهَى الْعِلْمِ وَمَبْلَغَ الرِّضَا وَزِنَةَ الْعَرْشِ، لَا مَلْجَأَ وَلَا مَنْجَا مِنَ اللهِ إِلَّا إِلَيْهِ. سُبْحَانَ اللهِ عَدَدَ الشَّفْعِ وَالْوَتْرِ وَعَدَدَ كَلِمَاتِ اللهِ التَّامَّاتِ كُلِّهَا. نَسْأَلُكَ السَّلَامَةَ بِرَحْمَتِكَ يَا أَرْحَمَ الرَّاحِمِينَ. وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ الْعَلِيِّ الْعَظِيمِ. وَصَلَّى اللهُ تَعَالَى عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلَّمَ.",
    latin: "Subhanallahi mil'al mizani wa muntahal 'ilmi wa mablaghar ridha wa zinatal 'arsyi, la malja'a wa la manja minallahi illa ilaih. Subhanallahi 'adadasy syaf'i wal watri wa 'adada kalimatillahit tamammati kulliha. Nas'alukas salamata birahmatika ya arhamar rahimin. Wa la hawla wa la quwwata illa billahil 'aliyyil 'azhim. Wa shallallahu ta'ala 'ala sayyidina Muhammadin wa 'ala alihi wa shahbihi wa sallam.",
    terjemah: "Maha Suci Allah sepenuh timbangan, sedalam ilmu, sebatas ridho dan seberat Arsy. Tidak ada tempat berlindung dan menyelamatkan diri dari Allah kecuali hanya kepada-Nya. Maha Suci Allah sebanyak hitungan genap dan ganjil, dan sebanyak kalimat Allah yang sempurna semuanya. Kami memohon keselamatan dengan rahmat-Mu wahai Dzat Yang Paling Penyayang di antara semua yang penyayang. Tiada daya dan upaya kecuali dengan pertolongan Allah Yang Maha Tinggi lagi Maha Agung. Dan semoga Allah Ta'ala melimpahkan shalawat dan salam kepada junjungan kami Nabi Muhammad, serta keluarga dan sahabatnya.",
    sumber: "Umum",
    kategori: "Penting"
  },
  {
    judul: "Doa Setelah Sholat Fardhu",
    arab: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ\n\nاَلْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ، حَمْدًا يُوَافِي نِعَمَهُ وَيُكَافِئُ مَزِيدَهُ، يَا رَبَّنَا لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ.\n\nاَللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ، وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ، صَلَاةً وَسَلَامًا دَائِمَيْنِ مُتَلَازِمَيْنِ إِلَى يَوْمِ الدِّينِ.\n\nاَللَّهُمَّ اغْفِرْ لَنَا ذُنُوبَنَا كُلَّهَا، دِقَّهَا وَجِلَّهَا، أَوَّلَهَا وَآخِرَهَا، عَلَانِيَتَهَا وَسِرَّهَا، وَاغْفِرْ لَنَا وَلِوَالِدِينَا، وَلِأَجْدَادِنَا وَجَدَّاتِنَا، وَلِمَشَايِخِنَا وَأَسَاتِذَتِنَا، وَلِمَنْ لَهُ حَقٌّ عَلَيْنَا، وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ، وَالْمُسْلِمِينَ وَالْمُسْلِمَاتِ، الْأَحْيَاءِ مِنْهُمْ وَالْأَمْوَاتِ.\n\nاَللَّهُمَّ إِنَّا نَسْأَلُكَ إِيمَانًا كَامِلًا، وَيَقِينًا صَادِقًا، وَقَلْبًا خَاشِعًا، وَلِسَانًا ذَاكِرًا، وَرِزْقًا وَاسِعًا حَلَالًا طَيِّبًا، وَعِلْمًا نَافِعًا، وَعَمَلًا صَالِحًا مُتَقَبَّلًا، وَتَوْبَةً نَصُوحًا قَبْلَ الْمَوْتِ، وَرَاحَةً عِنْدَ الْمَوْتِ، وَمَغْفِرَةً وَرَحْمَةً بَعْدَ الْمَوْتِ.\n\nاَللَّهُمَّ هَوِّنْ عَلَيْنَا فِي سَكَرَاتِ الْمَوْتِ، وَثَبِّتْنَا عِنْدَ السُّؤَالِ، وَاجْعَلْ قُبُورَنَا رَوْضَةً مِنْ رِيَاضِ الْجَنَّةِ، وَلَا تَجْعَلْهَا حُفْرَةً مِنْ حُفَرِ النَّارِ، وَالنَّجَاةَ مِنَ النَّارِ، وَالْعَفْوَ عِنْدَ الْحِسَابِ.\n\nاَللَّهُمَّ اجْعَلْ خَيْرَ أَعْمَارِنَا آخِرَهَا، وَخَيْرَ أَعْمَالِنَا خَوَاتِيمَهَا، وَخَيْرَ أَيَّامِنَا يَوْمَ لِقَائِكَ.\n\nاَللَّهُمَّ اجْعَلْنَا مِنْ عِبَادِكَ الصَّالِحِينَ، وَمِنْ أَوْلِيَائِكَ الْمُتَّقِينَ، وَمِنْ حِزْبِكَ الْمُفْلِحِينَ، وَمِنْ عِبَادِكَ الْمُخْلَصِينَ.\n\nاَللَّهُمَّ أَصْلِحْ لَنَا أَزْوَاجَنَا وَذُرِّيَّاتِنَا، وَاجْعَلْهُمْ مِنْ أَهْلِ الصَّلَاحِ وَالْفَلَاحِ، وَمِنْ حَمَلَةِ الْقُرْآنِ وَالْعِلْمِ، وَاجْعَلْهُمْ قُرَّةَ أَعْيُنٍ لَنَا فِي الدُّنْيَا وَالْآخِرَةِ.\n\nاَللَّهُمَّ احْفَظْ أَوْلَادَنَا مِنْ كُلِّ سُوءٍ وَفِتْنَةٍ، وَوَفِّقْهُمْ لِطَاعَتِكَ، وَارْزُقْهُمُ الْعِلْمَ النَّافِعَ وَالْعَمَلَ الصَّالِحَ، وَاجْعَلْهُمْ مِنَ الصَّالِحِينَ الْمُصْلِحِينَ.\n\nاَللَّهُمَّ بَارِكْ لَنَا فِي أَهْلِنَا وَأَزْوَاجِنَا وَأَوْلَادِنَا، وَأَلِّفْ بَيْنَ قُلُوبِنَا، وَاجْعَلْ بُيُوتَنَا بُيُوتًا سَكِينَةً وَمَوَدَّةً وَرَحْمَةً.\n\nاَللَّهُمَّ أَصْلِحْ لَنَا دِينَنَا الَّذِي هُوَ عِصْمَةُ أَمْرِنَا، وَأَصْلِحْ لَنَا دُنْيَانَا الَّتِي فِيهَا مَعَاشُنَا، وَأَصْلِحْ لَنَا آخِرَتَنَا الَّتِي فِيهَا مَعَادُنَا، وَاجْعَلِ الْحَيَاةَ زِيَادَةً لَنَا فِي كُلِّ خَيْرٍ، وَاجْعَلِ الْمَوْتَ رَاحَةً لَنَا مِنْ كُلِّ شَرٍّ.\n\nاَللَّهُمَّ احْفَظْ بِلَادَنَا إِنْدُونِيسِيَا، وَأَدِمْ عَلَيْهَا نِعْمَةَ الْإِيمَانِ وَالْإِسْلَامِ وَالْأَمْنِ وَالْأَمَانِ وَالسَّلَامَةِ وَالِاسْتِقْرَارِ، وَادْفَعْ عَنَّا الْغَلَاءَ وَالْوَبَاءَ وَالرِّبَا وَالزِّنَا وَالزَّلَازِلَ وَالْمِحَنَ وَسُوءَ الْفِتَنِ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ.\n\nاَللَّهُمَّ احْفَظْ أَهْلَ بُولَوْ تِيجَا بَارَاتْ، وَأَدِمْ عَلَيْهِمْ نِعْمَةَ الْإِيمَانِ وَالْإِسْلَامِ وَالْأَمْنِ وَالْأَمَانِ وَالصِّحَّةِ وَالْعَافِيَةِ وَالْبَرَكَةِ.\n\nاَللَّهُمَّ ادْفَعْ عَنْ أَهْلِ بُولَوْ تِيجَا بَارَاتْ الْبَلَاءَ وَالْوَبَاءَ وَالْفِتَنَ وَالْمِحَنَ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ.\n\nاَللَّهُمَّ بَارِكْ فِي أَرْزَاقِهِمْ وَمَعَايِشِهِمْ وَزُرُوعِهِمْ وَبُحُورِهِمْ وَصَيْدِهِمْ، وَاجْعَلْهُمْ مِنْ عِبَادِكَ الشَّاكِرِينَ.\n\nاَللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِهِمْ، وَاجْمَعْهُمْ عَلَى الْخَيْرِ وَالتَّقْوَى، وَاصْرِفْ عَنْهُمُ الشِّقَاقَ وَالنِّزَاعَ وَالْفُرْقَةَ.\n\nاَللَّهُمَّ اجْعَلْ بُولَوْ تِيجَا بَارَاتْ بَلَدًا آمِنًا مُطْمَئِنًّا، سَخَاءً رَخَاءً، وَاحْفَظْ أَهْلَهُ مِنْ كُلِّ سُوءٍ وَمَكْرُوهٍ.\n\nاَللَّهُمَّ وَفِّقْ قَادَتَهُ وَعُلَمَاءَهُ وَأَئِمَّتَهُ وَشَبَابَهُ وَنِسَاءَهُ وَأَطْفَالَهُ لِمَا تُحِبُّ وَتَرْضَى، وَاجْعَلْهُمْ مِنْ أَهْلِ الْخَيْرِ وَالصَّلَاحِ وَالْفَلَاحِ.\n\nرَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً إِنَّكَ أَنْتَ الْوَهَّابُ.\n\nرَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ.\n\nرَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا.\n\nرَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا.\n\nرَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ.\n\nرَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ.\n\nوَصَلَّى اللَّهُ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلَّمَ.\n\nسُبْحَانَ رَبِّكَ رَبِّ الْعِزَّةِ عَمَّا يَصِفُونَ وَسَلَامٌ عَلَى الْمُرْسَلِينَ وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ.",
    latin: "Bismillahir rahmaanir rahiim.\n\nAlhamdulillaahi rabbil 'aalamiin, hamdan yuwaafii ni'amahu wayukaafi'u maziidah, yaa rabbanaa lakal hamdu kamaa yanbaghii lijalaali wajhika wa 'adhiimi sulthaanik.\n\nAllahumma shalli wa sallim wa baarik 'alaa sayyidinaa Muhammad, wa 'alaa aali sayyidinaa Muhammad, shalaatan wa salaaman daa'imayni mutalaazimayni ilaa yaumid diin.\n\nAllahummaghfir lanaa dzunuubanaa kullahaa, diqqahaa wa jillahaa, awwalahaa wa aakhirahaa, 'alaaniyatahaa wa sirrahaa, waghfir lanaa waliwaalidiinaa, wali ajdaadinaa wa jaddaatinaa, walimasyayikhinaa wa asaatidzatinaa, waliman lahu haqqun 'alaynaa, walil mu'miniina wal mu'minaat, wal muslimiina wal muslimaat, al ahyaai minhum wal amwaat.\n\nAllahumma innaa nas'aluka iimaanan kaamilaa, wa yaqiinan shaadiqaa, wa qalban khaasyi'aa, wa lisaanan dzaakiraa, wa rizqan waasi'an halaalan thayyibaa, wa 'ilman naafi'aa, wa 'amalan shaalihaan mutaqabbalaa, wa taubatan nashuuhaan qablal maut, wa raahatan 'indal maut, wa maghfiratan wa rahmatan ba'dal maut.\n\nAllahumma hawwin 'alainaa fii sakaraatil maut, wa tsabbitnaa 'indas su'aal, waj'al qubuuranaa raudhatan min riyaadhil jannah, wa laa taj'alhaa hufratan min hufarin naar, wan najaata minan naar, wal 'afwa 'indal hisaab.\n\nAllahummaj'al khayra a'maarinaa aakhirahaa, wa khayra a'maalinaa khawaatiimahaa, wa khayra ayyaaminaa yauma liqaa'ik.\n\nAllahummaj'alnaa min 'ibaadikas shaalihiin, wa min auliyaa'ikal muttaqiin, wa min hizbikal muflihiin, wa min 'ibaadikal mukhlishiin.\n\nAllahumma ashlih lanaa azwajanaa wa dzurriyyaatinaa, waj'alhum min ahlish shalaahi wal falaah, wa min hamalatil qur'aani wal 'ilm, waj'alhum qurrata a'yunin lanaa fid dunyaa wal aakhirah.\n\nAllahummahfadh auladanaa min kulli suu'in wa fitnah, wa waffiqhum lithaa'atik, warzuqhumul 'ilman naafi'a wal 'amalash shaalih, waj'alhum minash shaalihiinal mushlihiin.\n\nAllahumma baarik lanaa fii ahlinaa wa azwaajinaa wa aulaadinaa, wa allif bayna quluubinaa, waj'al buyuutanaa buyuutan sakiinatan wa mawaddatan wa rahmatan.\n\nAllahumma ashlih lanaa diinanal ladzii huwa 'ishmatu amrinaa, wa ashlih lanaa dunyaanal latii fiihaa ma'aasyunaa, wa ashlih lanaa aakhiratanal latii fiihaa ma'aadunaa, waj'alil hayaata ziyaadatan lanaa fii kulli khayr, waj'alil mauta raahatan lanaa min kulli syarr.\n\nAllahummahfadh bilaadanaa Induuniisiyaa, wa adim 'alaihaa ni'matal iimaani wal islaami wal amni wal amaani was salaamati wal istiqraar, wadfa' 'annal ghalaa'a wal wabaa'a war ribaa waz zinaa waz zalaazila wal mihana wa suu'al fitani maa dhahara minhaa wamaa bathan.\n\nAllahummahfadh ahla Pulau Tiga Barat, wa adim 'alaihim ni'matal iimaani wal islaami wal amni wal amaani wash shihhati wal 'aafiyati wal barakah.\n\nAllahummadfa' 'an ahli Pulau Tiga Barat al balaa'a wal wabaa'a wal fitana wal mihana maa dhahara minhaa wamaa bathan.\n\nAllahumma baarik fii arzaaqihim wa ma'aayishihim wa zuruu'ihim wa buhuurihim wa shaydihim, waj'alhum min 'ibaadikasy syaakiriin.\n\nAllahumma allif bayna quluubihim, wajma'hum 'alal khayri wat taqwaa, washrif 'anhumusy syiqaqa wan nizaa'a wal furqah.\n\nAllahummaj'al Pulau Tiga Barat baladan aaminan muthma'innaa, sakhaa'an rakhaa'aa, wahfadh ahlahu min kulli suu'in wa makruuh.\n\nAllahumma waffiq qaadatahu wa 'ulamaa'ahu wa a'immatahu wa syabaabahu wa nisaa'ahu wa athfaalahu limaa tuhibbu wa tardhaa, waj'alhum min ahlil khayri wash shalaahi wal falaah.\n\nRabbanaa laa tuzigh quluubanaa ba'da idz hadaitanaa wahab lanaa min ladunka rahmatan innaka antal wahhaab.\n\nRabbanaa dhalamnaa anfusanaa wa in lam taghfir lanaa wa tarhamnaa lanakuunanna minal khaasiriin.\n\nRabbanaa aatinaa min ladunka rahmatan wa hayyi' lanaa min amrinaa rasyadaa.\n\nRabbanaa hab lanaa min azwaajinaa wa dzurriyyaatinaa qurrata a'yunin waj'alnaa lil muttaqiina imaamaa.\n\nRabbanaa aatinaa fid dunyaa hasanatan wa fil aakhirati hasanatan wa qinaa 'adhaaban naar.\n\nRabbanaa taqabbal minnaa innaka antas samii'ul 'aliim, wa tub 'alainaa innaka antat tawwaabur rahiim.\n\nWa shallallaahu 'alaa sayyidinaa Muhammadin wa 'alaa aalihi wa shahbihi wa sallam.\n\nSubhaana rabbika rabbil 'izzati 'ammaa yashifuun, wa salaamun 'alal mursaliin, walhamdulillaahi rabbil 'aalamiin.",
    terjemah: "Dengan menyebut nama Allah Yang Maha Pengasih lagi Maha Penyayang.\n\nSegala puji bagi Allah, Tuhan semesta alam, dengan pujian yang sebanding dengan nikmat-nikmat-Nya dan menjamin tambahannya. Ya Tuhan kami, bagi-Mu segala puji sebagaimana layaknya keagungan wajah-Mu dan kebesaran kekuasaan-Mu.\n\nYa Allah, limpahkanlah rahmat, keselamatan, dan keberkahan kepada junjungan kami Nabi Muhammad, dan kepada keluarga junjungan kami Nabi Muhammad, dengan rahmat dan keselamatan yang kekal dan terus-menerus hingga hari kiamat.\n\nYa Allah, ampunilah semua dosa-dosa kami, yang kecil maupun yang besar, yang pertama maupun yang terakhir, yang terang-terangan maupun yang tersembunyi. Dan ampunilah kami, kedua orang tua kami, kakek-nenek kami, guru-guru kami, ustaz-ustaz kami, orang-orang yang memiliki hak atas kami, serta seluruh mukminin dan mukminat, muslimin dan muslimat, baik yang masih hidup maupun yang telah meninggal.\n\nYa Allah, sesungguhnya kami memohon kepada-Mu iman yang sempurna, keyakinan yang benar, hati yang khusyuk, lisan yang selalu berdzikir, rezeki yang luas, halal, dan baik, ilmu yang bermanfaat, amal saleh yang diterima, taubat nasuha sebelum maut, ketenangan saat maut, serta ampunan dan rahmat setelah maut.\n\nYa Allah, ringankanlah kami dalam menghadapi sakaratul maut, teguhkanlah kami saat ditanya (di alam kubur), jadikanlah kuburan kami sebagai taman dari taman-taman surga, dan jangan Engkau jadikan lubang dari lubang-lubang neraka. Selamatkanlah kami dari api neraka dan berilah ampunan saat hisab.\n\nYa Allah, jadikanlah sebaik-baik umur kami pada akhirnya, sebaik-baik amal kami pada penutupnya, dan sebaik-baik hari kami adalah hari saat berjumpa dengan-Mu.\n\nYa Allah, jadikanlah kami termasuk hamba-hamba-Mu yang saleh, wali-wali-Mu yang bertakwa, golongan-Mu yang beruntung, dan hamba-hamba-Mu yang ikhlas.\n\nYa Allah, perbaikilah pasangan-pasangan dan keturunan-keturunan kami, jadikanlah mereka dari golongan orang-orang yang saleh dan beruntung, dan dari para pembawa Al-Qur'an dan ilmu, serta jadikanlah mereka penyejuk hati kami di dunia dan di akhirat.\n\nYa Allah, jagalah anak-anak kami dari segala keburukan dan fitnah, berilah mereka taufik untuk taat kepada-Mu, karuniakanlah kepada mereka ilmu yang bermanfaat dan amal yang saleh, dan jadikanlah mereka termasuk orang-orang yang saleh lagi memperbaiki orang lain.\n\nYa Allah, berkahilah kami pada keluarga kami, pasangan-pasangan kami, dan anak-anak kami, satukanlah hati-hati kami, dan jadikanlah rumah-rumah kami sebagai rumah yang penuh dengan ketenangan, kasih sayang, dan rahmat.\n\nYa Allah, perbaikilah agama kami yang menjadi penjaga urusan kami, perbaikilah dunia kami yang di dalamnya ada penghidupan kami, perbaikilah akhirat kami yang kepadanya kami kembali. Jadikanlah kehidupan ini sebagai tambahan bagi kami dalam setiap kebaikan, dan jadikanlah kematian sebagai tempat istirahat bagi kami dari segala keburukan.\n\nYa Allah, jagalah negara kami Indonesia, dan langgengkanlah nikmat iman, Islam, keamanan, keselamatan, dan stabilitas padanya. Hindarkanlah kami dari paceklik, wabah, riba, zina, gempa bumi, cobaan, dan fitnah yang buruk, baik yang tampak maupun yang tersembunyi.\n\nYa Allah, jagalah penduduk Pulau Tiga Barat, dan langgengkanlah kepada mereka nikmat iman, Islam, keamanan, keselamatan, kesehatan, kesejahteraan, dan keberkahan.\n\nYa Allah, tolaklah dari penduduk Pulau Tiga Barat ini bala bencana, wabah penyakit, berbagai macam fitnah dan cobaan baik yang nampak maupun yang tersembunyi.\n\nYa Allah, berkahilah rezeki, penghidupan, pertanian, lautan, dan hasil tangkapan mereka. Jadikanlah mereka hamba-hamba-Mu yang pandai bersyukur.\n\nYa Allah, satukanlah hati mereka, kumpulkan mereka di atas kebaikan dan ketakwaan, serta jauhkan dari mereka perpecahan, perselisihan, dan permusuhan.\n\nYa Allah, jadikanlah Pulau Tiga Barat ini negeri yang aman, tenteram, makmur, dan sejahtera. Peliharalah penduduknya dari segala macam keburukan dan hal-hal yang tidak menyenangkan.\n\nYa Allah, berikanlah taufik kepada para pemimpin, ulama, imam, pemuda, wanita, dan anak-anaknya kepada apa yang Engkau cintai dan ridhai. Jadikanlah mereka dari golongan ahli kebaikan, kesalehan, dan keberuntungan.\n\nYa Tuhan kami, janganlah Engkau condongkan hati kami kepada kesesatan setelah Engkau berikan petunjuk kepada kami, dan karuniakanlah rahmat dari sisi-Mu. Sesungguhnya Engkaulah Yang Maha Pemberi.\n\nYa Tuhan kami, kami telah menzalimi diri kami sendiri. Jika Engkau tidak mengampuni kami dan memberi rahmat kepada kami, niscaya kami termasuk orang-orang yang merugi.\n\nYa Tuhan kami, berikanlah rahmat kepada kami dari sisi-Mu dan sempurnakanlah petunjuk yang lurus bagi kami dalam urusan kami.\n\nYa Tuhan kami, anugerahkanlah kepada kami pasangan dan keturunan kami sebagai penyenang hati, dan jadikanlah kami pemimpin bagi orang-orang yang bertakwa.\n\nYa Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan peliharalah kami dari siksa api neraka.\n\nYa Tuhan kami, terimalah (amal) dari kami, sesungguhnya Engkaulah Yang Maha Mendengar lagi Maha Mengetahui, dan terimalah taubat kami, sesungguhnya Engkaulah Yang Maha Penerima Taubat lagi Maha Penyayang.\n\nSemoga Allah melimpahkan rahmat kepada junjungan kami Nabi Muhammad, beserta keluarga dan sahabatnya.\n\nMaha Suci Tuhanmu, Tuhan Yang Maha Perkasa, dari apa yang mereka sifatkan. Dan kesejahteraan dilimpahkan atas para rasul. Dan segala puji bagi Allah, Tuhan semesta alam.",
    sumber: "Umum",
    kategori: "Sholat"
  },
  {
    judul: "Doa Setelah Sholat Dhuha",
    arab: "اَللَّهُمَّ إِنَّ الضُّحَاءَ ضُحَاؤُكَ، وَالْبَهَاءَ بَهَاؤُكَ، وَالْجَمَالَ جَمَالُكَ، وَالْقُوَّةَ قُوَّتُكَ، وَالْقُدْرَةَ قُدْرَتُكَ، وَالْعِصْمَةَ عِصْمَتُكَ. اَللَّهُمَّ إِنْ كَانَ رِزْقِي فِي السَّمَاءِ فَأَنْزِلْهُ، وَإِنْ كَانَ فِي الأَرْضِ فَأَخْرِجْهُ، وَإِنْ كَانَ مُعْسِرًا فَيَسِّرْهُ، وَإِنْ كَانَ حَرَامًا فَطَهِّرْهُ، وَإِنْ كَانَ بَعِيدًا فَقَرِّبْهُ، بِحَقِّ ضُحَائِكَ وَبَهَائِكَ وَجَمَالِكَ وَقُوَّتِكَ وَقُدْرَتِكَ، آتِنِي مَا آتَيْتَ عِبَادَكَ الصَّالِحِينَ.",
    latin: "Allahumma innadh-dhuha'a dhuha'uka, wal-baha'a baha'uka, wal-jamala jamaluka, wal-quwwata quwwatuka, wal-qudrata qudratuka, wal-'ismata 'ismatuka. Allahumma in kana rizqi fis-sama'i fa_anzilhu, wa in kana fil-ardhi fa_akhrijhu, wa in kana mu'siran fayassirhu, wa in kana haraman fathahhirhu, wa in kana ba'idan faqarribhu, bihaqqi dhuha'ika wa baha'ika wa jamalika wa quwwatika wa qudratika, atini ma ataita 'ibadakash-shalihin.",
    terjemah: "Ya Allah, sesungguhnya waktu dhuha adalah waktu dhuha-Mu, keagungan adalah keagungan-Mu, keindahan adalah keindahan-Mu, kekuatan adalah kekuatan-Mu, kekuasaan adalah kekuasaan-Mu, dan penjagaan adalah penjagaan-Mu. Ya Allah, jika rezekiku masih di langit, turunkanlah; jika di bumi, keluarkanlah; jika sulit, mudahkanlah; jika haram, sucikanlah; jika jauh, dekatkanlah. Berkat waktu dhuha, keagungan, keindahan, kekuatan, dan kekuasaan-Mu, limpahkanlah kepadaku segala yang Engkau limpahkan kepada hamba-hamba-Mu yang saleh.",
    sumber: "Umum",
    kategori: "Sholat"
  },
  {
    judul: "Doa Setelah Sholat Tahajud",
    arab: "اَللَّهُمَّ رَبَّنَا لَكَ الْحَمْدُ، أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ، لَكَ مُلْكُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ، أَنْتَ نُورُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ. أَنْتَ الْحَقُّ، وَوَعْدُكَ الْحَقُّ، وَلِقَاؤُكَ حَقٌّ، وَقَوْلُكَ حَقٌّ، وَالْجَنَّةُ حَقٌّ، وَالنَّارُ حَقٌّ، وَالنَّبِيُّونَ حَقٌّ، وَمُحَمَّدٌ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ حَقٌّ، وَالسَّاعَةُ حَقٌّ. اَللَّهُمَّ لَكَ أَسْلَمْتُ، وَبِكَ آمَنْتُ، وَعَلَيْكَ تَوَكَّلْتُ، وَإِلَيْكَ أَنَبْتُ، وَبِكَ خَاصَمْتُ، وَإِلَيْكَ حَاكَمْتُ، فَاغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ، وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ، أَنْتَ الْمُقَدِّمُ وَأَنْتَ الْمُؤَخِّرُ، لَا إِلَهَ إِلَّا أَنْتَ.",
    latin: "Allahumma rabbana lakal-hamd, anta qayyimus-samawati wal-ardhi wa man fihinna, wa lakal-hamd, laka mulkus-samawati wal-ardhi wa man fihinna, wa lakal-hamd, anta nurus-samawati wal-ardhi wa man fihinna, wa lakal-hamd. Antal-haqq, wa wa'dukal-haqq, wa liqa'uka haqq, wa qauluka haqq, wal-jannatu haqq, wan-naru haqq, wan-nabiyyuna haqq, wa Muhammadun shallallahu 'alaihi wa sallama haqq, was-sa'atu haqq. Allahumma laka aslamtu, wa bika amantu, wa 'alaika tawakkaltu, wa ilaika anabtu, wa bika khasamtu, wa ilaika hakamtu, faghfirli ma qaddamtu wama akhkhartu, wama asrartu wama a'lantu, antal-muqaddimu wa antal-mu'akhkhiru, la ilaha illa anta.",
    terjemah: "Ya Allah, bagi-Mu segala puji, Engkaulah penegak langit, bumi, dan apa yang ada di dalamnya. Bagi-Mu segala puji, milik-Mu kerajaan langit, bumi, dan apa yang ada di dalamnya. Bagi-Mu segala puji, Engkaulah cahaya langit, bumi, dan apa yang ada di dalamnya. Bagi-Mu segala puji. Engkaulah Al-Haq (Kebenaran), janji-Mu benar, pertemuan dengan-Mu benar, firman-Mu benar, surga benar, neraka benar, para nabi benar, Muhammad SAW benar, dan hari kiamat benar. Ya Allah, kepada-Mu aku berserah diri, kepada-Mu aku beriman, kepada-Mu aku bertawakal, kepada-Mu aku kembali, dengan nama-Mu aku membela diri, dan kepada-Mu aku berhukum. Maka ampunilah aku atas dosaku yang telah lalu dan yang akan datang, yang aku sembunyikan dan yang aku nyatakan. Engkaulah Yang Maha Terdahulu dan Engkaulah Yang Maha Terakhir, tiada Tuhan selain Engkau.",
    sumber: "HR. Bukhari & Muslim",
    kategori: "Sholat"
  }
];

export const ASMAUL_HUSNA = [
  { no: 1, arab: "الرَّحْمَنُ", latin: "Ar-Rahman", arti: "Maha Pengasih" },
  { no: 2, arab: "الرَّحِيمُ", latin: "Ar-Rahim", arti: "Maha Penyayang" },
  { no: 3, arab: "الْمَلِكُ", latin: "Al-Malik", arti: "Maha Merajai" },
  { no: 4, arab: "الْقُدُّوسُ", latin: "Al-Quddus", arti: "Maha Suci" },
  { no: 5, arab: "السَّلاَمُ", latin: "As-Salam", arti: "Maha Memberi Kesejahteraan" },
  { no: 6, arab: "الْمُؤْمِنُ", latin: "Al-Mu'min", arti: "Maha Memberi Keamanan" },
  { no: 7, arab: "الْمُهَيْمِنُ", latin: "Al-Muhaimin", arti: "Maha Mengatur" },
  { no: 8, arab: "الْعَزِيزُ", latin: "Al-Aziz", arti: "Maha Perkasa" },
  { no: 9, arab: "الْجَبَّارُ", latin: "Al-Jabbar", arti: "Maha Gagah" },
  { no: 10, arab: "الْمُتَكَبِّرُ", latin: "Al-Mutakabbir", arti: "Maha Memiliki Kebesaran" },
  { no: 11, arab: "الْخَالِقُ", latin: "Al-Khaliq", arti: "Maha Pencipta" },
  { no: 12, arab: "الْبَارِئُ", latin: "Al-Bari'", arti: "Maha Melepaskan" },
  { no: 13, arab: "الْمُصَوِّرُ", latin: "Al-Musawwir", arti: "Maha Membentuk Rupa" },
  { no: 14, arab: "الْغَفَّارُ", latin: "Al-Ghaffar", arti: "Maha Pengampun" },
  { no: 15, arab: "الْقَهَّارُ", latin: "Al-Qahhar", arti: "Maha Menundukkan" },
  { no: 16, arab: "الْوَهَّابُ", latin: "Al-Wahhab", arti: "Maha Pemberi Karunia" },
  { no: 17, arab: "الرَّزَّاقُ", latin: "Ar-Razzaq", arti: "Maha Pemberi Rezeki" },
  { no: 18, arab: "الْفَتَّاحُ", latin: "Al-Fattah", arti: "Maha Pembuka Rahmat" },
  { no: 19, arab: "الْعَلِيمُ", latin: "Al-Alim", arti: "Maha Mengetahui" },
  { no: 20, arab: "الْقَابِضُ", latin: "Al-Qabid", arti: "Maha Menyempitkan" },
  { no: 21, arab: "الْبَاسِطُ", latin: "Al-Basit", arti: "Maha Melapangkan" },
  { no: 22, arab: "الْخَافِضُ", latin: "Al-Khafid", arti: "Maha Merendahkan" },
  { no: 23, arab: "الرَّافِعُ", latin: "Ar-Rafi'", arti: "Maha Meninggikan" },
  { no: 24, arab: "الْمُعِزُّ", latin: "Al-Mu'izz", arti: "Maha Memuliakan" },
  { no: 25, arab: "الْمُذِلُّ", latin: "Al-Mudhill", arti: "Maha Menghinakan" },
  { no: 26, arab: "السَّمِيعُ", latin: "As-Sami'", arti: "Maha Mendengar" },
  { no: 27, arab: "الْبَصِيرُ", latin: "Al-Basir", arti: "Maha Melihat" },
  { no: 28, arab: "الْحَكَمُ", latin: "Al-Hakam", arti: "Maha Menetapkan" },
  { no: 29, arab: "الْعَدْلُ", latin: "Al-Adl", arti: "Maha Adil" },
  { no: 30, arab: "اللَّطِيفُ", latin: "Al-Latif", arti: "Maha Lembut" },
  { no: 31, arab: "الْخَبِيرُ", latin: "Al-Khabir", arti: "Maha Mengenal" },
  { no: 32, arab: "الْحَلِيمُ", latin: "Al-Halim", arti: "Maha Penyantun" },
  { no: 33, arab: "الْعَظِيمُ", latin: "Al-Azim", arti: "Maha Agung" },
  { no: 34, arab: "الْغَفُورُ", latin: "Al-Ghafur", arti: "Maha Pengampun" },
  { no: 35, arab: "الشَّكُورُ", latin: "Asy-Syakur", arti: "Maha Menerima Syukur" },
  { no: 36, arab: "الْعَلِيُّ", latin: "Al-Aliyy", arti: "Maha Tinggi" },
  { no: 37, arab: "الْكَبِيرُ", latin: "Al-Kabir", arti: "Maha Besar" },
  { no: 38, arab: "الْحَفِيظُ", latin: "Al-Hafiz", arti: "Maha Memelihara" },
  { no: 39, arab: "الْمُقِيتُ", latin: "Al-Muqit", arti: "Maha Pemberi Kecukupan" },
  { no: 40, arab: "الْحَسِيبُ", latin: "Al-Hasib", arti: "Maha Pembuat Perhitungan" },
  { no: 41, arab: "الْجَلِيلُ", latin: "Al-Jalil", arti: "Maha Luhur" },
  { no: 42, arab: "الْكَرِيمُ", latin: "Al-Karim", arti: "Maha Mulia" },
  { no: 43, arab: "الرَّقِيبُ", latin: "Ar-Raqib", arti: "Maha Mengawasi" },
  { no: 44, arab: "الْمُجِيبُ", latin: "Al-Mujib", arti: "Maha Mengabulkan" },
  { no: 45, arab: "الْوَاسِعُ", latin: "Al-Wasi'", arti: "Maha Luas" },
  { no: 46, arab: "الْحَكَمُ", latin: "Al-Hakim", arti: "Maha Bijaksana" },
  { no: 47, arab: "الْوَدُودُ", latin: "Al-Wadud", arti: "Maha Mengasihi" },
  { no: 48, arab: "الْمَجِيدُ", latin: "Al-Majid", arti: "Maha Mulia" },
  { no: 49, arab: "الْبَاعِثُ", latin: "Al-Ba'ith", arti: "Maha Membangkitkan" },
  { no: 50, arab: "الشَّهِيدُ", latin: "Asy-Syahid", arti: "Maha Menyaksikan" },
  { no: 51, arab: "الْحَقُّ", latin: "Al-Haqq", arti: "Maha Benar" },
  { no: 52, arab: "الْوَكِيلُ", latin: "Al-Wakil", arti: "Maha Memelihara" },
  { no: 53, arab: "الْقَوِيُّ", latin: "Al-Qawiyy", arti: "Maha Kuat" },
  { no: 54, arab: "الْمَتِينُ", latin: "Al-Matin", arti: "Maha Kokoh" },
  { no: 55, arab: "الْوَلِيُّ", latin: "Al-Waliyy", arti: "Maha Melindungi" },
  { no: 56, arab: "الْحَمِيدُ", latin: "Al-Hamid", arti: "Maha Terpuji" },
  { no: 57, arab: "الْمُحْصِي", latin: "Al-Muhsi", arti: "Maha Menghitung" },
  { no: 58, arab: "الْمُبْدِئُ", latin: "Al-Mubdi'", arti: "Maha Memulai" },
  { no: 59, arab: "الْمُعِيدُ", latin: "Al-Mu'id", arti: "Maha Mengembalikan" },
  { no: 60, arab: "الْمُحْيِي", latin: "Al-Muhyi", arti: "Maha Menghidupkan" },
  { no: 61, arab: "الْمُمِيتُ", latin: "Al-Mumit", arti: "Maha Mematikan" },
  { no: 62, arab: "الْحَيُّ", latin: "Al-Hayy", arti: "Maha Hidup" },
  { no: 63, arab: "الْقَيُّومُ", latin: "Al-Qayyum", arti: "Maha Mandiri" },
  { no: 64, arab: "الْوَاجِدُ", latin: "Al-Wajid", arti: "Maha Penemu" },
  { no: 65, arab: "الْمَاجِدُ", latin: "Al-Majid", arti: "Maha Mulia" },
  { no: 66, arab: "الْوَاحِدُ", latin: "Al-Wahid", arti: "Maha Tunggal" },
  { no: 67, arab: "الاَحَدُ", latin: "Al-Ahad", arti: "Maha Esa" },
  { no: 68, arab: "الصَّمَدُ", latin: "As-Samad", arti: "Maha Dibutuhkan" },
  { no: 69, arab: "الْقَادِرُ", latin: "Al-Qadir", arti: "Maha Kuasa" },
  { no: 70, arab: "الْمُقْتَدِرُ", latin: "Al-Muqtadir", arti: "Maha Menentukan" },
  { no: 71, arab: "الْمُقَدِّمُ", latin: "Al-Muqaddim", arti: "Maha Mendahulukan" },
  { no: 72, arab: "الْمُؤَخِّرُ", latin: "Al-Mu'akhkhir", arti: "Maha Mengakhirkan" },
  { no: 73, arab: "الأوَّلُ", latin: "Al-Awwal", arti: "Maha Permulaan" },
  { no: 74, arab: "الآخِرُ", latin: "Al-Akhir", arti: "Maha Akhir" },
  { no: 75, arab: "الظَّاهِرُ", latin: "Az-Zahir", arti: "Maha Nyata" },
  { no: 76, arab: "الْبَاطِنُ", latin: "Al-Batin", arti: "Maha Tersembunyi" },
  { no: 77, arab: "الْوَالِي", latin: "Al-Wali", arti: "Maha Memerintah" },
  { no: 78, arab: "الْمُتَعَالِي", latin: "Al-Muta'ali", arti: "Maha Tinggi" },
  { no: 79, arab: "الْبَرُّ", latin: "Al-Barr", arti: "Maha Penderma" },
  { no: 80, arab: "التَّوَّابُ", latin: "At-Tawwab", arti: "Maha Penerima Taubat" },
  { no: 81, arab: "الْمُنْتَقِمُ", latin: "Al-Muntaqim", arti: "Maha Pemberi Balasan" },
  { no: 82, arab: "الْعَفُوُّ", latin: "Al-Afuww", arti: "Maha Pemaaf" },
  { no: 83, arab: "الرَّؤُوفُ", latin: "Ar-Ra'uf", arti: "Maha Pengasuh" },
  { no: 84, arab: "مَالِكُ الْمُلْكِ", latin: "Malikul-Mulk", arti: "Maha Penguasa Kerajaan" },
  { no: 85, arab: "ذُو الْجَلاَلِ وَالإِكْرَامِ", latin: "Dzul-Jalali Wal-Ikram", arti: "Maha Memiliki Keagungan dan Kemuliaan" },
  { no: 86, arab: "الْمُقْسِطُ", latin: "Al-Muqsit", arti: "Maha Adil" },
  { no: 87, arab: "الْجَامِعُ", latin: "Al-Jami'", arti: "Maha Mengumpulkan" },
  { no: 88, arab: "الْغَنِيُّ", latin: "Al-Ghaniyy", arti: "Maha Kaya" },
  { no: 89, arab: "الْمُغْنِي", latin: "Al-Mughni", arti: "Maha Pemberi Kekayaan" },
  { no: 90, arab: "الْمَانِعُ", latin: "Al-Mani'", arti: "Maha Mencegah" },
  { no: 91, arab: "الضَّارُّ", latin: "Ad-Darr", arti: "Maha Penimpa Kemudharatan" },
  { no: 92, arab: "النَّافِعُ", latin: "An-Nafi'", arti: "Maha Pemberi Manfaat" },
  { no: 93, arab: "النُّورُ", latin: "An-Nur", arti: "Maha Bercahaya" },
  { no: 94, arab: "الْهَادِي", latin: "Al-Hadi", arti: "Maha Pemberi Petunjuk" },
  { no: 95, arab: "الْبَدِيعُ", latin: "Al-Badi'", arti: "Maha Pencipta Keindahan" },
  { no: 96, arab: "الْبَاقِي", latin: "Al-Baqi", arti: "Maha Kekal" },
  { no: 97, arab: "الْوَارِثُ", latin: "Al-Warith", arti: "Maha Mewarisi" },
  { no: 98, arab: "الرَّشِيدُ", latin: "Ar-Rasyid", arti: "Maha Pandai" },
  { no: 99, arab: "الصَّبُورُ", latin: "As-Sabur", arti: "Maha Penyabar" }
];
